[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "prod"
version = "0.1.0"
description = "Control power outlets and lab power supplies"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["argcomplete", "pyyaml"]

[project.optional-dependencies]
nge100 = ["pyvisa", "pyvisa-py"]

[project.scripts]
prod = "prod:main"

[tool.setuptools]
py-modules = ["prod", "anel", "nge100"]
